apiVersion: apps/v1
kind: Deployment
metadata:
  name: myserverapp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myserverapp
  template:
    metadata:
      labels:
        app: myserverapp
    spec:
      containers:
        - name: myserverapp-container
          image: myserverapp:v1
          ports:
            - containerPort: 3000
